Controllers/DoctorController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Hospitals.Data;
using parcial1_hospitales.Models;
using parcial1_hospitales.ViewModels;
using parcial1_hospitales.Services;
using Microsoft.AspNetCore.Authorization;

namespace Hospitals.Controllers
{
    public class DoctorController : Controller
    {

        private IDoctorService _doctorService;

        public DoctorController(IDoctorService doctorService)
        {
            _doctorService = doctorService;
        }

        // GET: Doctor
        [Authorize]
        public async Task<IActionResult> Index(string? filter, bool? isAvailable)
        {

            var doctors = _doctorService.GetAll(filter, isAvailable);

            var viewModel = new DoctorViewModel();
            viewModel.doctors = doctors;

            return View(viewModel);
        }
        
        // GET: Doctor/Details/5
        [Authorize(Roles = "senior,semisenior,junior")]
        public async Task<IActionResult> Details(int? id)
        {
            var doctor = await _doctorService.GetById(id);
            return View(doctor);
        }

        // GET: Doctor/Create
        [Authorize(Roles = "senior,semisenior")]
        public IActionResult Create()
        {
            ViewData["HospitalId"] = new SelectList(_doctorService.getContext().Hospitals, "Id", "Name");
            return View();
        }

        // POST: Doctor/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Name,Age,IsAvailable,Specialty,HospitalId")] Doctor doctor)
        {
            _doctorService.Create(doctor);
            return RedirectToAction(nameof(Index));
        }

        // GET: Doctor/Edit/5
        [Authorize(Roles = "senior,semisenior,junior")]
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _doctorService.getContext().Doctors == null)
            {
                return NotFound();
            }

            var doctor = await _doctorService.GetById(id);
            if (doctor == null)
            {
                return NotFound();
            }
            ViewData["HospitalId"] = new SelectList(_doctorService.getContext().Hospitals, "Id", "Name", doctor.HospitalId);
            return View(doctor);
        }

        // POST: Doctor/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "senior,semisenior,junior")]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Name,Age,IsAvailable,Specialty,HospitalId")] Doctor doctor)
        {
            if (id != doctor.Id)
            {
                return NotFound();
            }

            _doctorService.Update(doctor,id);
            return RedirectToAction(nameof(Index));
        }

        // GET: Doctor/Delete/5
        [Authorize(Roles = "senior")]
        public async Task<IActionResult> Delete(int? id)
        {
            var doctor = await _doctorService.GetById(id);
            if (doctor == null)
            {
                return NotFound();
            }

            return View(doctor);
        }

        // POST: Doctor/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "senior")]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var doctor = await _doctorService.GetById(id);
            if (doctor != null)
            {
                _doctorService.Delete(doctor);
            }
            
            return RedirectToAction(nameof(Index));
        }
    }
}

Controllers/PatientController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Hospitals.Data;
using parcial1_hospitales.Models;
using parcial1_hospitales.Services;
using parcial1_hospitales.ViewModels;
using Microsoft.AspNetCore.Authorization;

namespace Hospitals.Controllers
{
    public class PatientController : Controller
    {
        private readonly IPatientService _patientService;

        public PatientController(IPatientService patientService)
        {
            _patientService = patientService;
        }

        // GET: Patient
        [Authorize]
        public async Task<IActionResult> Index(string? filter)
        {
            var patients = _patientService.GetAll(filter);

            var viewModel = new PatientViewModel();
            viewModel.patients = patients;

            return View(viewModel);
        }

        // GET: Patient/Details/5
        [Authorize(Roles = "senior,semisenior,junior")]
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _patientService.getContext().Patients == null)
            {
                return NotFound();
            }

            var patient = await _patientService.GetById(id);
            if (patient == null)
            {
                return NotFound();
            }

            return View(patient);
        }

        // GET: Patient/Create
        [Authorize(Roles = "senior,semisenior")]
        public IActionResult Create()
        {
            return View();
        }

        // POST: Patient/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "senior,semisenior")]
        public async Task<IActionResult> Create([Bind("Id,Name,Age")] Patient patient)
        {
           
                _patientService.Create(patient);
                return RedirectToAction(nameof(Index));
            
        }

        // GET: Patient/Edit/5
        [Authorize(Roles = "senior,semisenior")]
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _patientService.getContext().Patients == null)
            {
                return NotFound();
            }

            var patient = await _patientService.GetById(id);
            if (patient == null)
            {
                return NotFound();
            }
            return View(patient);
        }

        // POST: Patient/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "senior,semisenior")]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Name,Age")] Patient patient)
        {
            if (id != patient.Id)
            {
                return NotFound();
            }

             _patientService.Update(patient,id);
            return RedirectToAction(nameof(Index));
        }

        // GET: Patient/Delete/5
        [Authorize(Roles = "senior")]
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _patientService.getContext().Patients == null)
            {
                return NotFound();
            }

            var patient = await _patientService.getContext().Patients
                .FirstOrDefaultAsync(m => m.Id == id);
            if (patient == null)
            {
                return NotFound();
            }

            return View(patient);
        }

        // POST: Patient/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "senior")]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_patientService.getContext().Patients == null)
            {
                return Problem("Entity set 'ApplicationDbContext.Patients'  is null.");
            }

            var partient = await _patientService.GetById(id);
            if (partient != null)
            {
                _patientService.Delete(partient);
            }
            
            return RedirectToAction(nameof(Index));
        }

        private bool PatientExists(int id)
        {
          return (_patientService.getContext().Patients?.Any(e => e.Id == id)).GetValueOrDefault();
        }

    }
}

Controllers/RolesController.cs
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using Hospitals.Models;
using Microsoft.AspNetCore.Identity;
using parcial1_hospitales.Services;
using Microsoft.AspNetCore.Authorization;

namespace Hospitals.Controllers;

public class RolesController : Controller
{

    private IRolesService _roleService;

    public RolesController(IRolesService service)
    {
        _roleService = service;
    }

    [Authorize]
    public IActionResult Index()
    {
        var users = _roleService.GetAll();
        return View(users);
    }

    [Authorize(Roles = "senior")]
    public IActionResult Create()
    {
        return View();
    }

    [HttpPost]
    [Authorize(Roles = "senior")]
    public IActionResult Create(string roleName)
    {
        if (!string.IsNullOrEmpty(roleName)) {
            var roleExists = _roleService.roleExists(roleName);
            if (!roleExists)
            {
                _roleService.create(roleName);
            }
        }
        return RedirectToAction("Index");
    }
}

Controllers/UsersController.cs
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using Hospitals.Models;
using Microsoft.AspNetCore.Identity;
using parcial1_hospitales.Services;
using parcial1_hospitales.Views.Users.ViewModels;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.AspNetCore.Authorization;

namespace Hospitals.Controllers;

public class UsersController : Controller
{
    private readonly ILogger<HomeController> _logger;
    private readonly UserManager<IdentityUser> _userManager;
    private readonly RoleManager<IdentityRole> _roleManager;

    public UsersController(
        ILogger<HomeController> logger,
        UserManager<IdentityUser> userManager,
        RoleManager<IdentityRole> roleManager)
    {
        _logger = logger;
        _userManager = userManager;
        _roleManager = roleManager;
    }

    [Authorize]
    public IActionResult Index()
    {
        //listar todos los usuarios
        var users = _userManager.Users.ToList();
        return View(users);
    }

    [Authorize(Roles = "senior")]
    public async Task<IActionResult> Edit(string id)
    {
        var user = await _userManager.FindByIdAsync(id);

        var userViewModel = new UserEditViewModel();
        userViewModel.UserName = user.UserName ?? string.Empty;
        userViewModel.Email = user.Email ?? string.Empty;
        userViewModel.Roles = new SelectList(_roleManager.Roles.ToList());

        return View(userViewModel);
    }

    [HttpPost]
    [Authorize(Roles = "senior")]
    public async Task<IActionResult> Edit(UserEditViewModel model)
    {
        var user = await _userManager.FindByNameAsync(model.UserName);

        if (user != null)
        {
            if (model.Role == null)
            {
                Console.WriteLine("model.Role is null");
            }

            await _userManager.AddToRoleAsync(user, model.Role);
        }
        else
        {
            Console.WriteLine("user is null");
        }

        var roles = await _userManager.GetRolesAsync(user);


        return RedirectToAction("Index");
    }

}

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Hospitales</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Hospitals.styles.css" asp-append-version="true" />
    <link href="~/css/bootstrap.min.css" rel="stylesheet" />
</head>
<body>
<header style="background: linear-gradient(to right, #007bff, #00bfff);">
    <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
        <div class="container-fluid">
            <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                    aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                <ul class="navbar-nav flex-grow-1">
                    <li class="nav-item">
                        <a class="nav-link text-dark" asp-area="" asp-controller="Hospital" asp-action="Index">Hospitales</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link text-dark" asp-area="" asp-controller="Doctor" asp-action="Index">Doctores</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link text-dark" asp-area="" asp-controller="Appointment" asp-action="Index">Citas</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link text-dark" asp-area="" asp-controller="Patient" asp-action="Index">Pacientes</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link text-dark" asp-area="" asp-controller="Users" asp-action="Index">Usuarios</a>
                    </li>
                     <li class="nav-item">
                        <a class="nav-link text-dark" asp-area="" asp-controller="Roles" asp-action="Index">Roles</a>
                    </li>
                </ul>
                <partial name="_LoginPartial" />
            </div>
        </div>
    </nav>
</header>

    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>